//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNNDataTables.Modules.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNNDataTables_CityWeather
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Temp { get; set; }
        public decimal High { get; set; }
        public decimal Low { get; set; }
    }
}
